[package]
name = "sruler"
version = "0.4.0"
edition = "2021"
rust-version = "1.81"
license = "GPL-3.0-or-later"
description = "a wayland screen ruler"

[dependencies]
anyhow = "1"
arboard = { version = "3", features = ["wayland-data-control"] }
eframe = { version = "0.34", default-features = false, features = ["glow", "wayland"] }
egui = "0.34"
image = "0.25"
wayland-client = "0.31"
wayland-protocols-wlr = { version = "0.2", features = ["client"] }
